services:
  - type: web
    name: bhiv-core
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r Backend/orchestration/unified_orchestration_system/requirements-api.txt
    startCommand: |
      cd Backend/orchestration/unified_orchestration_system && uvicorn bhiv_core_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      - key: AUDIO_DIR
        value: /var/data/bhiv_audio
      # Uncomment and set as you add services
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: bhiv-core-db
      #     property: connectionString
      # - key: REDIS_URL
      #   fromService:
      #     name: bhiv-redis
      #     type: redis
      # - key: GEMINI_API_KEY
      #   sync: false
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: ELEVENLABS_API_KEY
      #   sync: false
    disk:
      name: bhiv-audio-disk
      mountPath: /var/data
      sizeGB: 1

databases:
  - name: bhiv-core-db
    plan: free

